DROP TABLE book;
DROP TABLE person;

CREATE TABLE person (
    person_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR (100) UNIQUE,
    year INT CHECK (year > 1900 AND year <2020)
);

CREATE TABLE book (
    book_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR (100),
    author VARCHAR (30),
    year INT,
    person_id INT REFERENCES person(person_id) ON DELETE SET NULL
);
